export const metadata = {
  title: "Eyüp Sultan Camii Runnenberg",
  description: "Generated by create next app",
};
import './page.module.css'
export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        {children}
      </body>
    </html>
  );
}
